# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: lucene_accelerated_hnsw
groups:
  base:
    build:
      codec: ["Lucene101AcceleratedHNSWCodec"]
    search: {}
  test:
    build:
      codec: ["Lucene101AcceleratedHNSWCodec"]
    search: {}
